version: '3'
services:
  wp:
    build: .
    ports:
      - "1337:80"
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: trustno1
    volumes:
          - ./plugins:/var/www/html/wp-content/plugins
          - ./plugin-src:/var/www/html/wp-content/plugins/pursue
          - ./theme-src:/var/www/html/wp-content/themes/csusa
          - ./wp-content:/var/www/html/wp-content
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: trustno1
    volumes:
          - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: